cabal-version: 3.4
name: hs-bindgen-spike
version: 0.1.0.0
build-type: Simple
license: MPL-2.0

executable hs-bindgen-spike
  main-is: Main.hs
  hs-source-dirs: .
  other-modules: DuckDB
  default-language: GHC2021
  ghc-options: -threaded
  include-dirs: ../../duckdb-ffi/cbits
  extra-libraries: duckdb
  build-depends:
    base >=4.18 && <4.23,
    hs-bindgen ==1.0.0.0,
    hs-bindgen-runtime ==1.0.0.0,
